app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path("", include('student.urls')),
    path("", include('payment.urls')),
    path("", include('expense.urls')),
    path("", include('training.urls')),
    path("", include('resume_day.urls')),
]

payment/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('payments/received/', views.PaymentReceivedListView.as_view(), name='payment_received'),
    path('payments/received/<int:pk>/', views.PaymentReceivedDetailView.as_view(), name='payment_received_detail'),

    path('payments/pending/<int:pk>/', views.PaymentPendingDetails.as_view(), name='payment_pending_detail'),
    path('payments/pending/list/', views.PaymentsPending.as_view(), name='payment_pending_list'),

    path('payments/delay/list/', views.PaymentsDelayListView.as_view(), name='payment_delay_list'),
    path('payments/delay/created/', views.PaymentDelayCreatedView.as_view(), name='payment_delay_created'),
    path('payments/delay/<int:pk>/update/', views.PaymentDelayUpdateView.as_view(), name='payment_delay_update'),
    path('payments/delay/details/<int:pk>', views.PayentDelayDetailsView.as_view(), name='payment_delay_details'),
    path('payments/delay/delete/<int:pk>', views.PaymentDelayDeleteView.as_view(), name='payment_delay_delete'),


    path('payments/create/<int:student_id>/', views.PaymentCreateView.as_view(), name='payment_create'),
    path('pay/delay/create/<int:student_id>/', views.PayDelayCreatedView.as_view(), name='pay_delay_created'),
    path('pay/extra/create/', views.PayextraCreatedView.as_view(), name='pay_extra_created')
]

payment/models.py
from django.db import models
from student.models import Student


PAYMENT_METHOD_CHOICES = (
    ("Pix", "Pix"),
    ("Dinheiro", "Dinheiro"),
)


class PaymentPending(models.Model):
    student = models.ForeignKey(Student, on_delete=models.PROTECT, related_name="payment_pending_student")
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return str(self.student)


class PaymentReceived(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='payment_received_student')
    payment_method = models.CharField(max_length=30, choices=PAYMENT_METHOD_CHOICES)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)
    payment_source = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.student.name


class PaymentDelay(models.Model):
    MONTH_CHOICES = [
        ('01', 'Janeiro'),
        ('02', 'Fevereiro'),
        ('03', 'Março'),
        ('04', 'Abril'),
        ('05', 'Maio'),
        ('06', 'Junho'),
        ('07', 'Julho'),
        ('08', 'Agosto'),
        ('09', 'Setembro'),
        ('10', 'Outubro'),
        ('11', 'Novembro'),
        ('12', 'Dezembro'),
    ]
    student = models.ForeignKey(Student, on_delete=models.PROTECT, related_name='payment_delay_student')
    date = models.CharField(max_length=2, choices=MONTH_CHOICES)
    value_delay = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

payment/forms.py
from django import forms
from . import models


# Form responsavel por confirmar pagamentos e criar registros em pagamentos recebidos
class PaymentModelForm(forms.ModelForm):
    class Meta:
        model = models.PaymentReceived
        fields = ['payment_method', 'amount_paid']

        widgets = {
            'payment_method': forms.Select(attrs={'class': 'form-control', 'style': 'max-width: 100px;'}),
            'discount': forms.NumberInput(attrs={'class': 'form-control'}),
            'amount_paid': forms.NumberInput(attrs={'class': 'form-control'})

        }
        labels = {
            'payment_method': 'Método de pagamento',
            'discount': 'Desconto',
            'amount_paid': 'Valor pago'
        }

    def clean_amount_paid(self):

        amount_paid = self.cleaned_data.get('amount_paid')
        if amount_paid < 0:
            self.add_error('amount_paid', 'O valor recebido nao pode ser menor que zero')
        return amount_paid


# Forms responsavel por criar novos pagamentos extras em pagamentos recebidos
class PayExtraModelForm(forms.ModelForm):
    class Meta:
        model = models.PaymentReceived
        fields = ['student', 'payment_method', 'amount_paid']

        widgets = {
            'student': forms.Select(attrs={'class': 'form-control'}),
            'payment_method': forms.Select(attrs={'class': 'form-control', 'style': 'max-width: 100px;'}),
            'discount': forms.NumberInput(attrs={'class': 'form-control'}),
            'amount_paid': forms.NumberInput(attrs={'class': 'form-control'})

        }
        labels = {
            'student': 'Aluno',
            'payment_method': 'Método de pagamento',
            'discount': 'Desconto',
            'amount_paid': 'Valor pago'
        }


# Form Resposanvel por fazer update em pagamentos atrasados
class PaymentUpdate(forms.ModelForm):
    class Meta:
        model = models.PaymentDelay
        fields = ['value_delay']

        widgets = {
            'value_delay': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'value_delay': 'Valor atrasado',
        }


# Form responsavel por criar novos pendecias de pagamento em pagamentos atrasados
class PaymentDelayModelForm(forms.ModelForm):
    class Meta:
        model = models.PaymentDelay
        fields = ['student', 'date', 'value_delay']

        widgets = {
            'student': forms.Select(attrs={'class': 'form-control'}),
            'date': forms.DateInput(attrs={'class': 'form-control'}),
            'value_delay': forms.NumberInput(attrs={'class': 'form-control'}),

        }
        labels = {
            'student': 'Aluno',
            'date': 'Data referencia',
            'value_delay': 'Valor em atraso',
        }

payment/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from . import models
from student.models import Student
from . import forms
import datetime


class PaymentsPending(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.PaymentPending
    template_name = 'payment_pending/payments_pending_list.html'
    context_object_name = 'payments_pending'
    paginate_by = 10
    permission_required = 'payment.view_paymentpending'

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get('name')

        if name:
            queryset = queryset.filter(student__name__icontains=name)

        return queryset


class PaymentPendingDetails(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.PaymentPending
    template_name = 'payment_pending/payment_pending_details.html'
    context_object_name = 'payment'
    permission_required = 'payment.view_paymentpending'


class PaymentReceivedListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.PaymentReceived
    template_name = 'payment_received/payment_received.html'
    context_object_name = 'payments_received'
    paginate_by = 10
    permission_required = 'payment.view_paymentreceived'

    def get_year(self):
        """Verifica a data de criação a partir de 2025 para adicionar nas opções de filtros"""
        first_year = 2025
        today_year = datetime.date.today().year

        return list(range(first_year, today_year + 1))

    # Recuperando o contexto de ano para usar no input de filtro de ano
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['years'] = self.get_year()

        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get('name')

        # Filtro pelo nome do aluno
        if name:
            queryset = queryset.filter(student__name__icontains=name)

        # Filtro por mês e ano
        month = self.request.GET.get('month')
        year = self.request.GET.get('year')

        if month and year:
            # Filtrando por mês e ano
            queryset = queryset.filter(
                created_at__month=month,
                created_at__year=year
            )
        elif month:
            # Filtrando apenas pelo mês
            queryset = queryset.filter(created_at__month=month)
        elif year:
            # Filtrando apenas pelo ano
            queryset = queryset.filter(created_at__year=year)

        return queryset


class PaymentReceivedDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.PaymentReceived
    template_name = 'payment_received/payment_received_detail.html'
    context_object_name = 'pendingpayment'
    permission_required = 'payment.view_paymentreceived'


class PaymentCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.PaymentReceived
    form_class = forms.PaymentModelForm
    template_name = 'payment_received/payment_create.html'
    success_url = reverse_lazy('payment_pending_list')
    permission_required = 'payment.add_paymentreceived'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        student_id = self.kwargs['student_id']
        student = get_object_or_404(Student, id=student_id)
        context['student'] = student
        return context

    def form_valid(self, form):
        form.instance.student = get_object_or_404(Student, id=self.kwargs['student_id'])
        form.instance._source_view = "payment_create"  # Definindo a origem
        return super().form_valid(form)


# View resposavel pela criação de pagamento de pagamentos atrasados
class PayDelayCreatedView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.PaymentReceived
    template_name = 'payment_received/payment_delay_created.html'
    form_class = forms.PaymentModelForm
    success_url = reverse_lazy('payment_delay_list')
    permission_required = 'payment.add_paymentreceived'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        student_id = self.kwargs['student_id']
        student = get_object_or_404(Student, id=student_id)
        context['student'] = student

        payment_delay = get_object_or_404(models.PaymentDelay, student=student_id)
        context['payment_delay'] = payment_delay
        return context

    def form_valid(self, form):
        student = get_object_or_404(Student, id=self.kwargs['student_id'])  # Obtendo o estudante
        form.instance.student = student  # Associando o pagamento ao estudante
        form.instance._source_view = "pay_delay_created"  # Definindo a origem
        return super().form_valid(form)


class PayextraCreatedView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.PaymentReceived  # Corrigido de "models" para "model"
    template_name = 'payment_received/pay_extra_created.html'
    form_class = forms.PayExtraModelForm
    success_url = reverse_lazy('payment_pending_list')
    permission_required = 'payment.add_paymentreceived'


class PaymentsDelayListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.PaymentDelay
    template_name = 'payment_delay/payment_delay_list.html'
    context_object_name = 'payments_delay'
    paginate_by = 10
    permission_required = 'payment.view_paymentdelay'


class PaymentDelayCreatedView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.PaymentDelay
    template_name = 'payment_delay/payment_delay_created.html'
    form_class = forms.PaymentDelayModelForm
    success_url = reverse_lazy('payment_delay_list')
    permission_required = 'payment.add_paymentdelay'


class PayentDelayDetailsView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.PaymentDelay
    template_name = 'payment_delay/payment_delay_details.html'
    permission_required = 'payment.view_paymentdelay'


class PaymentDelayUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = models.PaymentDelay
    template_name = 'payment_delay/payment_delay_update.html'
    form_class = forms.PaymentUpdate
    success_url = reverse_lazy('payment_delay_list')
    permission_required = 'payment.change_paymentdelay'


class PaymentDelayDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = models.PaymentDelay
    template_name = 'payment_delay/payment_delay_delete.html'
    success_url = reverse_lazy('payment_delay_list')
    permission_required = 'payment.delete_paymentdelay'

payment/templates/payment_delay/payment_delay_created.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="max-width: 500px;">
    <h3>Novo pagamento em atraso</h3>
    <div class=" border p-3 container">
        <div class="mb-3"></div>
        <form method="post" class="position-relative">
            {% csrf_token %}
            {{form.as_p}}
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn border p-2 mt-3">Salvar</button>
                <a href="{% url 'payment_delay_list' %}" class="btn border p-2 mt-3">Voltar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

payment/templates/payment_delay/payment_delay_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="max-width: 500px;">
    <h3>Deletar Despesa</h3>
    <div class=" border p-3">
        <form method="post" class="position-relative">
            {% csrf_token %}
            <span>Você tem certeza que deseja deletar a mensalidade atrasada de <strong class="text-danger">{{paymentdelay.student.name}}</strong> no valor de <strong class="text-danger">{{paymentdelay.value_delay}}</strong></span>
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn border p-2 mt-3">Deletar</button>
                <a href="{% url 'payment_delay_list' %}" class="btn border p-2 mt-3">Voltar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

payment/templates/payment_delay/payment_delay_details.html
{% extends "base.html" %}

{% block content %}
<div style="max-width: 500px; margin: 0 auto;">
    <h2>Detalhes Cobrança </h2>
    <div class=" border p-3 container">
        <div>
            <h2>{{paymentdelay.student.name}}</h2>
            <span><strong>Valor a pagar R$: </strong> {{ paymentdelay.value_delay }}</span><br>
            <div class="m-3"></div>
            <div>
                <a href="{% url 'payment_create' paymentdelay.id %}">
                    <button class="btn btn-primary">Registrar Pagamento</button>
                </a>
            </div>
            <div class="d-flex justify-content-between"><a href="{% url 'payment_delay_list' %}" class="btn border p-2 mt-3">Voltar</a></div>
        </div>
    </div>
    {% endblock %}

payment/templates/payment_delay/payment_delay_list.html
{% extends "base.html" %}
{% block content %}
<h1>Pagamentos Atrasados </h1>
<div class="row gy-3">
    <!-- Formulário de pesquisa -->
    <div class="col-md-6">
        <form action="{% url 'payment_pending_list' %}" method="get">
            <div class="input-group">
                <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name }}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>

    <!-- Botões de ação -->
    <div class="col-md-6 d-flex justify-content-between flex-wrap gap-2">
        <a href="{% url 'payment_received' %}">
            <button class="btn btn-outline-warning">Pagamentos Recebidos</button>
        </a>
        <a href="{% url 'payment_pending_list' %}"><button class="btn btn-outline-warning">Pagamentos pendentes</button></a>
        <a href="{% url 'payment_delay_created' %}" class="text-decoration-none">
            <button class="btn btn-primary d-flex align-items-center gap-2">
                <i class="bi bi-plus-lg"></i>
                <span>Pagamento em atraso</span>
            </button>
        </a>


    </div>
</div>
<div class="m-3"></div>
<div class="table-responsive">
    <table class="table table-striped table-bordered text-center">
        <thead>
            <tr>
                <th>Aluno</th>
                <th>Valor a pagar</th>
                <th>Mês referência</th>
                <th>Registrar</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            {% for payment in payments_delay %}
            <tr>
                <td>{{ payment.student.name}}</td>
                <td>R${{ payment.value_delay|floatformat:2}}</td>
                <td>{{ payment.date }} | {{payment.get_date_display}} </td>
                <td>
                    <a href="{% url 'pay_delay_created' payment.student.id %}">
                        <button class="btn btn-primary">Registrar Pagamento</button>
                    </a>
                </td>
                <td>
                    <a href="{% url 'payment_delay_details' payment.student.id %}" class="p-2">
                        <i class="bi bi-eye bg-info p-1 text-dark rounded"></i>
                    </a>
                    <a href="{% url 'payment_delay_update' payment.student.id %}"><i class="bi bi-pencil bg-warning p-1 text-dark rounded"></i></a>
                    <a href="{% url 'payment_delay_delete' payment.id %}" class="p-2">
                        <i class="bi bi-archive-fill p-1 bg-danger text-light rounded"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include 'components/_pagination.html' %}
{% endblock %}

payment/templates/payment_delay/payment_delay_update.html
{% extends "base.html" %}

{% block content %}
<div style="max-width: 500px; margin: 0 auto;">
    <h3>Atualização Mensalidade atrasada</h3>
    <div class=" border p-3 container">
        <h1>{{paymentdelay.student.name}}</h1>
        <form method="post" class="position-relative">
            {% csrf_token %}
            {{form.as_p}}
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn border p-2 mt-3">Salvar</button>
                <a href="{% url 'payment_delay_list' %}" class="btn border p-2 mt-3">Voltar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}