app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path("", include('student.urls')),
    path("", include('payment.urls')),
    path("", include('expense.urls')),
    path("", include('training.urls')),
    path("", include('resume_day.urls')),
]

training/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('training/list/', views.TrainingListView.as_view(), name='training_list'),
    path('training/create/', views.TrainingCreateView.as_view(), name='training_create'),
    path('training/<int:pk>/detail/', views.TrainingDetailsView.as_view(), name='training_detail'),
    path('training/<int:pk>/update/', views.TrainingUpdateView.as_view(), name='training_update'),
    path('training/<int:pk>/delete/', views.TrainingDeleteView.as_view(), name='training_delete'),

    path('location/training/list/', views.LocationTrainingListView.as_view(), name='location_training_list'),
    path('location/training/create/', views.LocationTrainingCreateView.as_view(), name='location_training_create'),
    path('location/training/<int:pk>/update', views.LocationTrainingUpdateView.as_view(), name='location_training_update'),
    path('location/training/<int:pk>/detail', views.LocationTrainingDetailsView.as_view(), name='location_training_detail'),
    path('location/training/<int:pk>/delete', views.LocationTrainingDeleteView.as_view(), name='location_training_delete'),
]

expense/models.py
from django.db import models

STATUS_INSTALLMENT_CHOICES = (
    ('Pago', 'Pago'),
    ('Pendente', 'Pendente'),
)


class Expense(models.Model):
    name = models.TextField(max_length=400)
    value = models.DecimalField(max_digits=10, decimal_places=2)
    installment_count = models.PositiveIntegerField(default=1)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name


class Installment(models.Model):
    expense = models.ForeignKey(Expense, on_delete=models.CASCADE, related_name="installments")
    installment_number = models.PositiveIntegerField()
    installment_value = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=40, choices=STATUS_INSTALLMENT_CHOICES, default='Pendente')
    due_date = models.DateField()
    date_payment = models.DateField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    update_at = models.DateField(auto_now=True)

training/models.py
from django.db import models
from student.models import Student


class LocationTraining(models.Model):
    name = models.CharField(max_length=200)
    quantity_training = models.IntegerField(default=0, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class TrainingClass(models.Model):
    DAYS_CHOICES = (
        ('seg', 'Segunda-Feira'),
        ('ter', 'Terça-Feira'),
        ('qua', 'Quarta-Feira'),
        ('qui', 'Quinta-Feira'),
        ('sex', 'Sexta-Feira'),
        ('sab', 'Sabádo'),
        ('dom', 'Domingo'),
    )
    student = models.ManyToManyField(Student, related_name='training_classes')
    location = models.ForeignKey(LocationTraining, on_delete=models.PROTECT, related_name='location_training')
    time = models.TimeField()
    day = models.CharField(max_length=40, choices=DAYS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['day', 'time']

    def __str__(self):
        return f"{self.get_day_display()} - {self.time} ({self.location})"

training/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models


class TrainingModelForm(forms.ModelForm):
    class Meta:
        model = models.TrainingClass
        fields = ['student', 'time', 'day', 'location']

        widgets = {
            'student': forms.SelectMultiple(attrs={'class': 'form-select'}),
            'time': forms.TimeInput(attrs={'class': 'form-control'}),
            'day': forms.Select(attrs={'class': 'form-control'}),
            'location': forms.Select(attrs={'class': 'form-control'}),
        }

        labels = {
            'student': 'Alunos',
            'time': 'Horário',
            'day': 'Dia',
            'location': 'Local'
        }

    def clean(self):
        cleaned_data = super().clean()
        time = cleaned_data.get('time')
        day = cleaned_data.get('day')

        if day and time:
            queryset = models.TrainingClass.objects.filter(day=day, time=time)

            # Se estiver atualizando um treino, excluímos ele da verificação
            if self.instance and self.instance.pk:
                queryset = queryset.exclude(pk=self.instance.pk)

            if queryset.exists():
                raise ValidationError("Já existe um treino para este dia e hora")

        return cleaned_data


class LocationModelForm(forms.ModelForm):
    class Meta:
        model = models.LocationTraining
        fields = ['name', ]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', }),
        }

        labels = {
            'name': 'Nome',
        }

training/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from . import models
from student.models import Student
from . import forms

"""View de treinos"""


class TrainingListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.TrainingClass
    template_name = 'training/training_list.html'
    context_object_name = 'trainings'
    permission_required = 'training.view_trainingclass'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        trainings = context['trainings']

        # Dividir os treinos por dia
        context['training_days'] = {
            'seg': trainings.filter(day='seg'),
            'ter': trainings.filter(day='ter'),
            'qua': trainings.filter(day='qua'),
            'qui': trainings.filter(day='qui'),
            'sex': trainings.filter(day='sex'),
            'sab': trainings.filter(day='sab'),
            'dom': trainings.filter(day='dom'),
        }
        # Capturando quantidade de treinos em cada local
        brasil = 0
        criciuma = 0
        for training in context['trainings']:
            if training.location.name == "Arena Brasil":
                brasil += 1
            elif training.location.name == "Arena Criciuma":
                criciuma += 1
        context['brasil'] = brasil
        context['criciuma'] = criciuma
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get('name')

        if name:
            print(f'Filtramos por {name}')
            queryset = queryset.filter(student__name__icontains=name).distinct()
        return queryset


class TrainingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.TrainingClass
    template_name = 'training/training_create.html'
    form_class = forms.TrainingModelForm
    success_url = reverse_lazy('training_list')
    permission_required = 'training.add_trainingclass'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Filtra os estudantes cujo status não seja "Parou"
        context['students'] = Student.objects.exclude(status="Parou")

        return context


class TrainingDetailsView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.TrainingClass
    template_name = 'training/training_details.html'
    permission_required = 'training.view_trainingclass'


class TrainingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = models.TrainingClass
    template_name = 'training/training_update.html'
    form_class = forms.TrainingModelForm
    success_url = reverse_lazy('training_list')
    permission_required = 'training.change_trainingclass'


class TrainingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = models.TrainingClass
    template_name = 'training/training_delete.html'
    success_url = reverse_lazy('training_list')
    permission_required = 'training.delete_trainingclass'


"""Views de local de treino"""


class LocationTrainingListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.LocationTraining
    template_name = 'location_training/location_training_list.html'
    context_object_name = 'locations'
    paginate_by = 10
    permission_required = 'training.view_locationtraining'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Verifica se já existem pelo menos dois locais de treino
        if models.LocationTraining.objects.count() < 2:
            # Se não existirem, cria dois locais padrão
            models.LocationTraining.objects.create(name="Arena Brasil")
            models.LocationTraining.objects.create(name="Arena Criciuma")

        return context


class LocationTrainingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.LocationTraining
    template_name = 'location_training/location_training_create.html'
    form_class = forms.LocationModelForm
    success_url = reverse_lazy('location_training_list')
    permission_required = 'training.add_locationtraining'


class LocationTrainingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = models.LocationTraining
    template_name = 'location_training/location_training_update.html'
    form_class = forms.LocationModelForm
    success_url = reverse_lazy('location_training_list')
    permission_required = 'training.change_locationtraining'


class LocationTrainingDetailsView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.LocationTraining
    template_name = 'location_training/location_training_details.html'
    permission_required = 'training.view_locationtraining'


class LocationTrainingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = models.LocationTraining
    template_name = 'location_training/location_training_delete.html'
    success_url = reverse_lazy('location_training_list')
    permission_required = 'training.delete_locationtraining'

training/templates/training/training_create.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="max-width: 500px;">
    <h3>Nova Turma</h3>
    <div class=" border p-3 container">
        <div class="mb-3"></div>
        <form method="post" class="position-relative">
            {% csrf_token %}
            {{form.as_p}}
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn border p-2 mt-3">Salvar</button>
                <a href="{% url 'training_list' %}" class="btn border p-2 mt-3">Voltar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

training/templates/training/training_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="max-width: 500px;">
    <h3>Deletar Despesa</h3>
    <div class=" border p-3">
        <form method="post" class="position-relative">
            {% csrf_token %}
            <span>Você tem certeza que deseja deletar a turma de <strong class="text-danger">{{trainingclass.get_day_display}}</strong> das <strong class="text-danger">{{trainingclass.time}}</strong></span>
            <br>
            <span>Alunos na turma: </span> <br>
            {% for student in trainingclass.student.all %}
            <span><strong>Aluno {{ forloop.counter }}:</strong> {{ student.name }}</span><br>
            {% empty %}
            <span>Nenhum aluno nesta turma.</span>
            {% endfor %}
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn border p-2 mt-3">Deletar</button>
                <a href="{% url 'expense_list' %}" class="btn border p-2 mt-3">Voltar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

training/templates/training/training_details.html
{% extends "base.html" %}

{% block content %}
<div style="max-width: 500px; margin: 0 auto;">
    <h2>Detalhes da Turma</h2>
    <div class=" border p-3 container">
        <div>
            {% for student in trainingclass.student.all %}
            <div class="d-flex justify-content-between">
                <span><strong>Aluno {{ forloop.counter }}:</strong> {{ student.name }}</span> <span>{{student.class_days}}</span>
            </div>
            {% empty %}
            <span>Nenhum aluno nesta turma.</span>
            {% endfor %}
            <br>
            <span><strong>Dia: </strong>{{ trainingclass.get_day_display }}</span><br>
            <span><strong>Hora:: </strong>{{ trainingclass.time }}</span><br>
            <span><strong>local: </strong>{{ trainingclass.location }}</span><br>
        </div>
        <div class="d-flex justify-content-between"><a href="{#}" class="btn border p-2 mt-3">Editar</a><a href="{% url 'training_list' %}" class="btn border p-2 mt-3">Voltar</a></div>
    </div>
</div>
{% endblock %}

training/templates/training/training_list.html
{% extends "base.html" %}



{% block content %}

<div class="row">
    <div class="col-md-6">
        <div class="m-3"></div>
        <form action="{% url 'training_list' %}" method="get">
            <div class="input-group">
                <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name }}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <div class="m-3"></div>
        <!-- Span da Arena Criciuma -->
        <div class="d-flex">
            <span class="border p-2 text-white rounded shadow-sm me-2">
                Treinos Arena Criciuma: {{ criciuma }}
            </span>

            <!-- Span da Arena Brasil -->
            <span class="border p-2 text-white rounded shadow-sm ">
                Treinos Arena Brasil: {{ brasil }}
            </span>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="m-3"></div>
    <a href="{% url 'training_create' %}"><button class="btn btn-outline-warning">Nova turma</button></a>
    <a href="{% url 'location_training_list' %}"><button class="btn btn-outline-warning">Locais de treinos</button></a>
</div>



{% for day, trainings in training_days.items %}
{% if trainings %}
<div class="m-3"></div>
<h3>Treinos de {{ trainings.first.get_day_display }}</h3>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-lg-4 g-3">
    {% for training in trainings %}
    <div class="col">
        <div class="card h-100">
            <div class="card-header">
                <h5 class="card-title">{{ training.time }} / {{ training.location }}</h5>
            </div>
            <div class="card-body">
                {% for student in training.student.all %}
                <div class="d-flex justify-content-between">
                    <span>{{ student.name }}</span>
                </div>
                {% endfor %}
            </div>
            <div class="card-footer d-flex justify-content-between">
                <a href="{% url 'training_detail' training.id %}" class="p-2">
                    <i class="bi bi-eye bg-info p-1 text-dark rounded"></i>
                </a>
                <a href="{% url 'training_update' training.id %}" class="p-2">
                    <i class="bi bi-pencil bg-warning p-1 text-dark rounded"></i>
                </a>
                <a href="{% url 'training_delete' training.id %}" class="p-2">
                    <i class="bi bi-archive-fill p-1 bg-danger text-light rounded"></i>
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endfor %}
{% include 'components/_pagination.html' %}
{% endblock %}

training/templates/training/training_update.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="max-width: 500px;">
    <h3>Atualização de Turma</h3>
    <div class=" border p-3 container">
        <div class="mb-3"></div>
        <form method="post" class="position-relative">
            {% csrf_token %}
            {{form.as_p}}
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn border p-2 mt-3">Salvar</button>
                <a href="{% url 'training_list' %}" class="btn border p-2 mt-3">Voltar</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}