app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path("", include('student.urls')),
    path("", include('payment.urls')),
    path("", include('expense.urls')),
    path("", include('training.urls')),
    path("", include('resume_day.urls')),
]

student/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('student/list/', views.StudentListView.as_view(), name='student_list'),
    path('student/create/', views.StudentCreateView.as_view(), name='student_create'),
    path('student/<int:pk>/detail/', views.StudentDetailView.as_view(), name='student_detail'),
    path('student/<int:pk>/update/', views.StudentUpdateView.as_view(), name='student_update'),
]

student/models.py
from django.db import models
from decimal import Decimal
from django.db.models import Case, When, Value, IntegerField


GENDER_CHOICES = (
    ("F", "Feminino"),
    ("M", "Masculino"),
)
CLASS_DAYS_CHOICES = (
    ("Seg", "Segunda-feira"),
    ("Ter", "Terça-feira"),
    ("Qua", "Quarta-feira"),
    ("Qui", "Quinta-feira"),
    ("Sex", "sexta-feira"),
    ("Sab", "Sábado"),
    ("Dom", "Domingo"),
)
LEVEL_CHOICES = (
    ("A", "A"),
    ("B", "B"),
    ("C", "C"),
    ("D", "D"),
    ("I", "I"),
    ("PRO", "PRO"),
)
STATUS_CHOICES = (
    ("Regular", "Regular"),
    ("Parou", 'Parou'),
    ("Novo", "Novo"),
    ("Retornou", "Retornou")
)
STATUS_PAYMENT_CHOICES = (
    ('pendente', 'Pendente'),
    ('pago', 'Pago'),
)
BILLING_METHOD_CHOICES = (
    ('aula', 'Aula'),
    ('mensal', 'Mensal')
)


class Student(models.Model):
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES)
    class_days = models.TextField()
    class_quantity = models.IntegerField(blank=True, null=True, default=0)
    billing_method = models.CharField(max_length=10, choices=BILLING_METHOD_CHOICES)
    class_price = models. DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    monthly_fee = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    discount = models.IntegerField(default=0, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True, default=" ")
    level = models.CharField(max_length=3, choices=LEVEL_CHOICES)
    due_date = models.IntegerField()
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, blank=True, null=True)
    status_payment = models.CharField(max_length=10, choices=STATUS_PAYMENT_CHOICES, default='pendente')
    notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_att = models.DateTimeField(auto_now=True)

    @property
    def value_total(self):
        if self.billing_method == "aula":
            """Retorna o valor total sem desconto."""
            value = self.class_price * self.class_quantity
        if self.billing_method == "mensal":
            value = self.class_price
        return value

    @property
    def value_discount(self):
        """Retorna o valor total com desconto aplicado."""
        discount = self.discount / Decimal(100)
        value_discount = self.value_total * discount
        return self.value_total - value_discount

    class Meta:
        ordering = [
            Case(
                When(status='Parou', then=Value(4)),
                When(status='Retornou', then=Value(3)),
                When(status='Novo', then=Value(2)),
                When(status='Regular', then=Value(1)),
                default=Value(5),
                output_field=IntegerField()
            ),
        ]

    def __str__(self):
        return self.name

student/forms.py
from django import forms
from . import models
from student.models import CLASS_DAYS_CHOICES


class StudentModelForm(forms.ModelForm):
    class Meta:
        model = models.Student
        fields = [
            'name', 'gender', 'billing_method', 'class_price', 'discount',
            'phone_number', 'level', 'due_date', 'status', 'notes'
        ]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'billing_method': forms.Select(attrs={'class': 'form-control'}),
            'class_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'discount': forms.NumberInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'level': forms.Select(attrs={'class': 'form-control'}),
            'due_date': forms.NumberInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control', 'style': 'max-height: 50px;'}),
        }

        labels = {
            'name': 'Nome',
            'gender': 'Gênero',
            'billing_method': 'Método de cobrança',
            'class_days': 'Dias de aula',
            'discount': 'Desconto',
            'class_price': 'Valor',
            'phone_number': 'Telefone',
            'level': 'Categoria',
            'due_date': 'Vencimento',
            'notes': 'Observações',
        }

    class_days = forms.MultipleChoiceField(
        choices=CLASS_DAYS_CHOICES,
        widget=forms.CheckboxSelectMultiple,
        required=True,
        label="Dias de aula"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Se o objeto já existe e tem valores para 'class_days'
        if self.instance and self.instance.pk:
            # Convertendo os valores salvos (string) de volta para uma lista
            class_days = self.instance.class_days.split(',')
            self.fields['class_days'].initial = class_days

    # Tratamento de name
    def clean_name(self):
        name = self.cleaned_data.get("name")

        if not name:
            self.add_error('name', "Este campo é obrigatório.")
            return name

        name = name.strip()

        if not all(c.isalpha() or c.isspace() or c in "-'" for c in name):
            self.add_error('name', "Erro de digitação. Esse campo aceita apenas letras.")
            return name

        return name.title()

    # Tratamento de phone number
    def clean_phone_number(self):
        number = self.cleaned_data.get('phone_number')
        if number:
            number = ''.join(filter(str.isdigit, number))

            if len(number) != 11:
                self.add_error('phone_number', "Número inválido. O número deve ter 11 dígitos.")

        return number

    # Tratamento de discount
    def clean_discount(self):
        discount = self.cleaned_data.get('discount')
        if discount < 0 or discount > 100:
            self.add_error("discount", "Valor de desconto deve ser de 0 a 100")
        return discount

    # Tratando due date (vencimento)
    def clean_due_date(self):
        due_date = self.cleaned_data.get('due_date')
        if due_date < 1 or due_date > 30:
            self.add_error('due_date', 'Data de vencimento inválida, informe uma data de 01 até 30')
        return due_date

    # Tratamento de valor
    def clean_class_price(self):
        class_price = self.cleaned_data.get('class_price')
        if class_price < 0:
            self.add_error('class_price', 'O valor da aula não pode ser menor que zero')
        return class_price

    def save(self, commit=True):
        # Obtendo a instância do modelo sem salvar ainda
        instance = super().save(commit=False)

        # Convertendo a lista de dias selecionados para string (separados por vírgulas)
        instance.class_days = ','.join(self.cleaned_data['class_days'])

        if instance.phone_number is None:
            instance.phone_number = " "

        # Salvando a instância no banco, se necessário
        if commit:
            instance.save()

        return instance

student/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.urls import reverse_lazy
from . import models
from . import forms


class StudentListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Student
    template_name = 'student_list.html'
    context_object_name = 'students'
    paginate_by = 10
    permission_required = 'student.view_student'

    def get_context_data(self, **kwargs):
        """Recuperando os choices de level_choices e gender_choices para ser usado em filtros"""
        context = super().get_context_data(**kwargs)
        context['level_choices'] = models.LEVEL_CHOICES
        context['gender_choices'] = models.GENDER_CHOICES

        return context

    def get_queryset(self):
        """Filtros por name, level e gender"""
        queryset = super().get_queryset()
        name = self.request.GET.get('name')
        level = self.request.GET.get('level')
        gender = self.request.GET.get('gender')

        if name:
            queryset = models.Student.objects.filter(name__icontains=name)
        if level:
            queryset = queryset.filter(level=level)
        if gender:
            queryset = queryset.filter(gender=gender)
        return queryset


class StudentCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Student
    form_class = forms.StudentModelForm
    template_name = 'student_create.html'
    success_url = reverse_lazy('student_list')
    permission_required = 'student.add_student'


class StudentDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Student
    template_name = 'student_detail.html'
    permission_required = 'student.view_student'


class StudentUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = models.Student
    form_class = forms.StudentModelForm
    template_name = 'student_update.html'
    success_url = reverse_lazy('student_list')
    permission_required = 'student.change_student'

student/templates/student_create.html
{% extends "base.html" %}

{% block content %}
<div class=" border p-3 container" style="max-width: 500px;">
    <h3>Novo Aluno</h3>
    <form method="post" class="position-relative">
        {% csrf_token %}
        {{form.as_p}}
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn border p-2 mt-3">Salvar</button>
            <a href="{% url 'student_list' %}" class="btn border p-2 mt-3">Voltar</a>
        </div>
    </form>
</div>
{% endblock %}

student/templates/student_detail.html
{% extends "base.html" %}

{% block content %}
<div style="max-width: 500px; margin: 0 auto;">
    <h2>Detalhes do aluno(a)</h2>
    <div class=" border p-3 container">
        <div>
            <h2>{{student.name}}</h2>
            <span><strong>Método de Cobrança: </strong>{{ student.get_billing_method_display }}</span><br>
            <span><strong>Gênero: </strong>{{student.get_gender_display}}</span><br>
            <span><strong>Dias de treino: </strong>{{student.class_days}}</span><br>
            <span><strong>Quantidade de treinos: </strong>{{student.class_quantity}}</span><br>
            <span><strong>Preço por aula: </strong>{{student.class_price}}</span><br>
            <span><strong>Desconto: </strong>{{student.discount}}%</span><br>
            <span><strong>Número de telefone: </strong>{{student.phone_number}}</span><br>
            <span><strong>Categoria: </strong>{{student.level}}</span><br>
            <span><strong>Data de vencimento: </strong>{{student.due_date}}</span><br>
            <span><strong>Observação: </strong>{{student.note}}</span><br>
        </div>
        <div class="d-flex justify-content-between"><a href="{% url 'student_update' student.id %}" class="btn border p-2 mt-3">Editar</a><a href="{% url 'student_list' %}" class="btn border p-2 mt-3">Voltar</a></div>
    </div>
</div>
{% endblock %}

student/templates/student_list.html
{% extends "base.html" %}

{% block content %}
<h1> Alunos </h1>
<div class="row">
    <form action="{% url 'student_list' %}" method="get" class="col-md-6">
        <div class="input-group">
            <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name }}">
            <button type="submit" class="btn btn-primary">
                <i class="bi bi-search"></i>
            </button>
        </div>
        <div class="input-group mt-2">
            <select class="form-select" name="level" id="level" aria-placeholder="Categoria">
                <option value="" {% if not request.GET.level %} selected {% endif %}>Todas Categoria</option>
                {% for value, label in level_choices %}
                <option value="{{ value }}" {% if value in request.GET.level %} selected {% endif %}>{{ label }}</option>

                {% endfor %}
            </select>
            <select class="form-select" name="gender" id="gender" aria-placeholder="Gênero">
                <option value="{{value}}" {% if not request.GET.gender %} selected {% endif %}>Todos Gêneros</option>
                {% for value, label in gender_choices %}
                <option value="{{value}}" {% if value in request.GET.gender %} selected {% endif %}>{{label}}</option>
                {% endfor %}
            </select>
            <button type="submit" class="btn btn-primary">
                <i class="bi bi-filter"></i>Filtrar
            </button>
        </div>
        <div class="m-3"></div>
    </form>

    {% if perms.student.add_student %}
    <div class="col-md-6">
        <a href="{% url 'student_create' %}"><button class="btn btn-outline-warning">Novo Aluno</button></a>
    </div>
    {% endif %}
</div>
<div class="m-3"></div>
<div class="table-responsive">
    <table class="table table-striped table-bordered text-center">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Gênero</th>
                <th>Método de Cobrança</th>
                <th>Treinos</th>
                <th>Nº aulas</th>
                <th>Preço aula</th>
                <th>Desconto</th>
                <th>Categoria</th>
                <th>Vencimento</th>
                <th>Status</th>
                <th>Telefone</th>
                <th>Descrição</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <td>{{student.name}}</td>
                <td>{{student.gender}}</td>
                <td>{{ student.get_billing_method_display }}</td>
                <td>{{student.class_days}}</td>
                <td>{{student.class_quantity}}</td>
                <td>{{student.class_price}}</td>
                <td>{{student.discount}}%</td>
                <td>{{student.level}}</td>
                <td>{{student.due_date}}</td>
                <td>{{student.status}}</td>
                <td>{{student.phone_number}}</td>
                <td>{{student.notes}}</td>
                <div>
                    <td>
                        {% if perms.student.view_student %}
                        <a href="{% url 'student_detail' student.id %}" class="p-2"><i class="bi bi-eye bg-info p-1 text-dark rounded"></i></a>
                        {% endif %}
                        {% if perms.student.change_student %}
                        <a href="{% url 'student_update' student.id %}"><i class="bi bi-pencil bg-warning p-1 text-dark rounded"></i></a>
                        {% endif %}
                    </td>
                </div>
            </tr>
            <tr>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include 'components/_pagination.html' %}
{% endblock %}

student/templates/student_update.html
{% extends "base.html" %}

{% block content %}
<div class=" border p-3 container" style="max-width: 500px;">
    <h3>Atualização Aluno(a)</h3>
    <form method="post" class="position-relative">
        {% csrf_token %}
        {{form.as_p}}
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn border p-2 mt-3">Salvar</button>
            <a href="{% url 'student_list' %}" class="btn border p-2 mt-3">Voltar</a>
        </div>
    </form>
</div>
{% endblock %}